// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnAoFpMPskYUsarwLOjgsZ8a8pasq7Qs',
    appId: '1:543429581746:web:98d451fa0045f042f522ab',
    messagingSenderId: '543429581746',
    projectId: 'calvcare-95205',
    authDomain: 'calvcare-95205.firebaseapp.com',
    databaseURL:
        'https://calvcare-95205-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calvcare-95205.appspot.com',
    measurementId: 'G-QHQGG29EPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQ6x_32kuRkGRIOWUiiXlE2AHMptEHh0',
    appId: '1:543429581746:android:ca5704ea6295e2f1f522ab',
    messagingSenderId: '543429581746',
    projectId: 'calvcare-95205',
    databaseURL:
        'https://calvcare-95205-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'calvcare-95205.appspot.com',
  );
}
